openapi: "3.0.1"
info:
  title: "OpenAPI definition"
  version: v0
servers:
  - url: "http://localhost:8080"
    description: "Generated server url"
paths:
  "/api/v1/{id}":
    get:
      tags:
        - "user-rest-controller"
      operationId: findById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/UserReadDto"
    put:
      tags:
        - "user-rest-controller"
      operationId: update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          "application/json":
            schema:
              "$ref": "#/components/schemas/UserCreateEditDto"
        required: true
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/UserReadDto"
  "/api/v1":
    get:
      tags:
        - "user-rest-controller"
      operationId: findAll
      parameters:
      - name: filter
        in: query
        required: true
        schema:
          "$ref": "#/components/schemas/UserFilter"
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/UserReadDto"
    post:
      tags:
        - "user-rest-controller"
      operationId: create
      requestBody:
        content:
          "application/json":
            schema:
              "$ref": "#/components/schemas/UserCreateEditDto"
        required: true
      responses:
        201:
          description: Created
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/UserReadDto"
  "/api/v1/{id}/delete":
    delete:
      tags:
        - "user-rest-controller"
      operationId: delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        204:
          description: "No Content"
components:
  schemas:
    UserCreateEditDto:
      type: object
      properties:
        username:
          type: string
        birthDate:
          type: string
          format: date
        firstname:
          maxLength: 64
          minLength: 3
          type: string
        lastname:
          type: string
        role:
          type: string
          enum:
            - USER
            - ADMIN
        companyId:
          type: integer
          format: int32
    CompanyReadDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
    UserReadDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        birthDate:
          type: string
          format: date
        firstname:
          type: string
        lastname:
          type: string
        role:
          type: string
          enum:
            - USER
            - ADMIN
        company:
            "$ref": "#/components/schemas/CompanyReadDto"
    UserFilter:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        birthDate:
          type: string
          format: date